### PR TITLE
feat: marching cubes now handled uint64

### PR DESCRIPTION
**Pull request by william-silversmith**

### CODE REVIEW

**Comment by william-silversmith** [comment]
figure_1
Results of meshing 64-bit segmentation 1024x1024x100 volume using 256x256x100 chunks.

**Comment by william-silversmith** [comment]
Most of the memory usage of meshing is due to the `uint64_t` meshes accumulating in memory (and the simplification step). The data type of the input volume doesn't matter very much.

**Comment by william-silversmith** [comment]
Also tried jemalloc vs regular malloc on a single threaded process:

jemalloc:

jemalloc

Regular Malloc:

regular_malloc

**Comment by william-silversmith** [comment]
cMesher.cpp::get_mesh can probably be optimized to use 2x less memory. It's currently making a copy and then writing that copy into flattened version of that array into meshobj. Probably we could write a get_faces function that just wrote them in directly.

**Comment by chrisj** [comment]
I thought there were 32 bits to identify the chunk and 32 bits to identify the segment in the chunk so you would still be able to use uint32 for marching cubes.

**Comment by william-silversmith** [comment]
I have a branch were I do renumbering in the MeshTask, so often we can even get down to uint8 for representing the contents of a 512x512x512 cube (typical meshing size). I think we should be okay regardless, 512x512x512 has 134217728 memory locations, which fits in a uint32.

**Pull request merged**
