### PR TITLE
Remove layers added by RUN

### PR DESCRIPTION
**Pull request by valerianpereira**
Remove layers added by RUN - Improve in docker image size

### CODE REVIEW

**Comment by william-silversmith** [comment]
Hi Valerian! Thanks for the contribution. I tested the new Dockerfile and I think you might need to add some `&&` to make this idea work. How much space does this save? Thank you. :)

**Comment by william-silversmith** [comment]
Hi Valerian, thanks for the update! 

I tested the changes but I'm not seeing a significant reduction in docker size. The increase in size is probably due to changes in dependencies. Would you be able to confirm the results below? If you see a reduction in size, I'll be happy to accept this PR. 

```
REPOSITORY                                        TAG                            IMAGE ID            CREATED             SIZE
<none>                                            <none>                         822e7be97ec0        6 minutes ago       1.83GB
seunglab/igneous                                  master                         8d75a3fa48ce        14 hours ago        1.79GB
```

**Comment by valerianpereira** [comment]
Correct @william-silversmith . The image size changes are not that significant. Just a minor change.
Given that, you can decide whether to accept/reject the PR :)

**Comment by william-silversmith** [comment]
Thanks for the PR Valerian. :)

**Pull request merged**
