### PR TITLE
Allow boto3 client parameters region_name and endpoint_url

### PR DESCRIPTION
**Pull request by chrisroat**
I needed this for local testing using a dockerized sqs queue, where the endpoint_url to boto3.client is required and credentials are not necessary.
https://hub.docker.com/r/roribio16/alpine-sqs/

### CODE REVIEW

**Comment by william-silversmith** [comment]
This is linked with https://github.com/seung-lab/python-task-queue/pull/26

**Comment by william-silversmith** [comment]
Thanks for the contribution Chris! We'll merge this once TaskQueue is.

**Comment by chrisroat** [comment]
Yes, this should not break current usage, but to use the new functionality you will need the updated taskqueue.

(Though, I'm not sure it was actually functional before -- the "tag" parameter was not fully removed from task_execution.py)

**Comment by chrisroat** [comment]
What is the procedure for pushing a new docker image?  I was going to build one locally for my tests, but ran into a seeming need to access an upstream git repo!?  I haven't used pbr before.

Exception: Versioning for this project requires either an sdist tarball, or access to an upstream git repository. It's also possible that there is a mismatch between the package name in setup.cfg and the argument given to pbr.version.VersionInfo. Project name igneous was given, but was not able to be found.
    error in igneous setup command: Error parsing /igneous/setup.cfg: Exception: Versioning for this project requires either an sdist tarball, or access to an upstream git repository. It's also possible that there is a mismatch between the package name in setup.cfg and the argument given to pbr.version.VersionInfo. Project name igneous was given, but was not able to be found.

**Comment by william-silversmith** [comment]
I ran into this issue yesterday with another repo and I am not sure what is causing it. I was able to build igneous on master just now and pushed it to dockerhub.

**Comment by chrisroat** [comment]
Thanks!!!

**Comment by chrisroat** [comment]
What is the difference between the master and latest tags on docker hub?

**Comment by william-silversmith** [comment]
Use latest, I should delete master it's old.

**Pull request merged**
