### PR TITLE
Preparations for agglomeration meshing

### PR DESCRIPTION
**Pull request by nkemnitz**
* Fixed potential infinite recursion with `super(self.__class__, self)`. See [StackOverflow](https://stackoverflow.com/questions/18208683/when-calling-super-in-a-derived-class-can-i-pass-in-self-class)
* Consistent indentation in tasks.py, removed unnecessary imports
* Uncommented `HyperSquareTask` since clearly broken
* MeshTask now supports a remap table, instant generation of manifests (only useful if meshes are confined to a single chunk), and adjustable lower/higher chunk overlaps. Required for meshing agglomerations

### CODE REVIEW

**Comment by william-silversmith** [comment]
1) Why do you consider HyperSquareTask broken? I've used it in the past to import e2198 and zfish. I'm not sure we'll ever need it again, but that would be a different point of attack.
2) Maybe comment out rather than delete those imports which pertain only to BigArrayTask. The reason BigArrayTask is commented out is mainly because it has dependencies that cause installation problems. I'm sure there are less hacky ways to deal with that but I haven't had to work with BigArray in a while since Jingpeng moved over to CloudVolume. 
3) I guess it's justifiable to remove writeobj from the C++ code since we now have Python code to do it... 
4) If the previous mesh calculation was off, why did it match up with neuroglancer so well?

tbc

**Comment by nkemnitz** [comment]
>1. Why do you consider HyperSquareTask broken?

https://github.com/seung-lab/igneous/blob/32e04bb8e204c19eb205d7113044a1afc811331f/igneous/tasks.py#L440-L443
a) `storage` and `lib` are undefined
b) There is an `xrange` in the code, possibly other old Python2 code
c)

**Comment by william-silversmith** [comment]
Ah... I should have looked more closely. Yea, that corresponds to an
extremely old version of CloudVolume.

**Comment by nkemnitz** [comment]
#### 1. Why do you consider HyperSquareTask broken?
https://github.com/seung-lab/igneous/blob/32e04bb8e204c19eb205d7113044a1afc811331f/igneous/tasks.py#L440-L443
https://github.com/seung-lab/igneous/blob/32e04bb8e204c19eb205d7113044a1afc811331f/igneous/tasks.py#L477-L478
https://github.com/seung-lab/igneous/blob/32e04bb8e204c19eb205d7113044a1afc811331f/igneous/tasks.py#L500-L510
a) `storage` and `lib` are undefined
b) There is an `xrange` in the code, possibly other Python 2 remnants otherwhere
c) `CloudVolume()` is called with old parameters, `image` is undefined.

#### 2. Maybe comment out rather than delete those imports which pertain only to BigArrayTask.
OK, will add the ones for BigArrayTask and HyperSquareTask back in

#### 4. If the previous mesh calculation was off, why did it match up with neuroglancer so well?
The mesh calculation is the same as before. What changed is what the `max_simplification_error` represents:
Until now, the function assumed cube-shaped voxels of size 1x1x1. I guess it worked so far because we just tested several values until something looked pleasant? If the new code works as it should, the value now really represents the Hausdorff distance. Which in turn means, the results should be more predictable.

**Comment by nkemnitz** [comment]
Scratch Hausdorff distance... but a reasonable approximation thereof.

**Comment by nkemnitz** [comment]
@william-silversmith: Requires PR https://github.com/seung-lab/python-task-queue/pull/7

**Comment by nkemnitz** [comment]
@william-silversmith Tests pass

Just to reiterate: This will change how the `max_simplification_error` is interpreted when simplifying a mesh. The value now _should_ approximately be the maximum tolerable distance (in physical units) between original and simplified mesh. In other words: Values that previously looked nice (but meant nothing), will now likely produce garbage results.

**Comment by nkemnitz** [comment]
@william-silversmith Anything blocking this PR?

**Comment by william-silversmith** [comment]
Looks good to me. I'm not a fan of the automatic changes to ContrastNormalizationTask and LuminanceLevelsTask b/c we don't have tests for them yet. However, the changes look okay to me. 

One thing you might want to consider is adding a longer help description to MeshTask as you can no longer see all the options.

**Pull request merged**
